[compile_macvim_and_ycm_on_osx]

date      = "2014-09-29T18:00:42+08:00"
draft     = true
title     = "COMPILE MACVIM & YCM ON OSX"

tags      = ["Tool"]
platforms = ["MacOS"]
languages = ["Bash"]

[error_collection_bash]

date = "2014-11-07T09:24:33+08:00"
draft = true
title = "ERROR COLLECTION - BASH"

tags      = ["Shell"]
platforms = ["Linux", "MacOS", "Win"]
languages = ["Bash"]
series    = ["Error"]

[error_collection_ios]

date = "2015-02-07T09:24:33+08:00"
draft = true
title = "ERROR COLLECTION - IOS"

tags      = ["Dev"]
platforms = ["MacOS"]
languages = ["OC", "Swift"]
series    = ["Error"]

[error_collection_javascript]

date = "2014-11-07T09:24:33+08:00"
draft = true
title = "ERROR COLLECTION - JAVASCRIPT"

platforms = ["Web"]
languages = ["JavaScript"]
series    = ["Error"]

[error_collection_sh]

date = "2014-11-07T09:24:33+08:00"
draft = true
title = "ERROR COLLECTION - BASH"

tags      = ["Shell"]
platforms = ["Linux", "MacOS", "Win"]
languages = ["Bash"]
series    = ["Error"]

[my_vim_customization_policy]

date = "2014-10-30T10:15:08+08:00"
draft = true
title = "MY VIM CUSTOMIZATION POLICY"

tags      = ["Tool", "Vim"]
platforms = ["MacOS", "Win", "Linux"]
languages = ["Bash"]

[setup_my_archlinux_environment]

date = "2014-11-08T22:33:51+08:00"
draft = true
title = "SETUP MY ARCH LINUX ENVIRONMENT"

tags      = ["System", "Setup", "Awesome"]
platforms = ["Arch", "Linux"]
languages = ["Bash", "Lua"]
series    = ["Setup"]

[setup_my_aweseome_wm_environment]

date = "2014-11-05T09:28:07+08:00"
draft = true
title = "SETUP MY AWESOME WM ENVIRONMENT"

tags      = ["Tool", "Awesome", "Setup"]
platforms = ["Linux", "Arch"]
languages = ["Bash", "Lua"]
series    = ["Setup"]

[setup_my_cygwin_environment]

date  = "2014-11-05T09:26:59+08:00"
draft = true
title = "SETUP MY CYGWIN ENVIRONMENT"

tags      = ["Tool", "Shell", "Bash", "Zsh", "Setup"]
platforms = ["Win"]
languages = ["Bash"]
series    = ["Setup"]

[setup_my_vim_environment]

date = "2014-11-08T17:40:55+08:00"
draft = true
title = "SETUP MY VIM ENVIRONMENT"

tags      = ["Tool", "Vim", "Setup"]
platforms = ["Linux", "Arch", "MacOS", "Win"]
languages = ["Bash", "VimL"]
series    = ["Setup"]

[setup_my_zsh_environment]

date = "2014-11-05T09:34:11+08:00"
draft = true
title = "SETUP MY ZSH ENVIRONMENT"

tags      = ["Tool", "Shell", "Zsh", "Setup"]
platforms = ["Linux", "Win", "MacOS"]
languages = ["Bash"]
series    = ["Setup"]

[vim_chameleon_startup_menu]

date = "2014-09-29T15:57:37+08:00"
draft = true
title = "VIM CHAMELEON STARTUP MENU"

tags      = ["Tool", "Vim"]
platforms = ["MacOS", "Win", "Linux"]
languages = ["Bash"]

[cocoa_concurrency]

date        = "2014-09-24T22:18:21+08:00"
draft       = true
title       = "COCOA CONCURRENCY"
description = "concurrency supports provided on Apple platforms."

tags        = ["Cocoa", "Concurrency"]
languages   = ["ObjC", "Swift", "C"]
platforms   = ["iOS", "MacOS"]

[cocoa_threading]

author    = "Mudox"
date      = "2014-09-24T21:19:59+08:00"
draft     = true
title     = "COCOA THREADING"

tags      = ["Cocoa", "Concurrency"]
languages = ["ObjC", "Swift", "C"]
platforms = ["iOS", "MacOS"]

[git]

date      = "2014-10-02T03:36:12+08:00"
draft     = true
title     = "GIT MISC"

tags      = ["Git", "Tool"]
languages = ["Bash"]
platforms = ["MacOS", "Win", "Linux"]

[git_flow]

date      = "2014-09-28T16:38:26+08:00"
draft     = true
title     = "GIT FLOW"

tags      = ["Git", "Tool"]
languages = ["Bash"]
platforms = ["MacOS", "Win", "Linux"]

[go_stdlib_template]

date      = "2014-09-26T14:52:32+08:00"
draft     = true
title     = "GO'S TEMPLATE LIBRARY"

tags      = ["Libraries"]
languages = ["Go"]
platforms = ["MacOS", "Win", "Linux"]

[ios_notes_casting]

date = "2015-04-12T14:43:56+08:00"
draft = true
title = "iOS NOTES - CASTING"

tags      = ["Cocoa", "AppDev"]
languages = ["Swift", "ObjC"]
platforms = ["MacOS", "iOS"]

[ios_notes_keyboard]

author    = "Mudox"
date      = "2015-04-08T16:19:59+08:00"
draft     = true
title     = "iOS NOTES - KEYBOARD"

tags      = ["Cocoa", "AppDev"]
languages = ["ObjC", "Swift"]
platforms = ["iOS"]

[javascript_type_conversions]

date = "2014-10-28T11:33:15+08:00"
draft = true
title = "JAVASCRIPT TYPE CONVERSIONS"

languages = ["JavaScript"]
platforms = ["Web"]

[swift_features]

date = "2014-10-14T21:43:56+08:00"
draft = true
title = "SWIFT FEATURES"

languages = ["Swift"]
platforms = ["MacOS", "iOS"]

[swift_notes_function]

author    = "Mudox"
date      = "2015-04-13T16:26:59+08:00"
draft     = true
title     = "Swift NOTES - FUNCTION"

tags      = ["Cocoa", "AppDev"]
languages = ["ObjC", "Swift"]
platforms = ["iOS", "MacOS"]

[swift_oo]

date = "2014-10-29T21:43:56+08:00"
draft = true
title = "SWIFT OJECT-ORIENTED FEATURE"

languages = ["Swift"]
platforms = ["MacOS", "iOS"]

[web_page_layouts]

date = "2014-10-26T21:36:29+08:00"
draft = true
title = "WEB PAGE LAYOUTS"

languages = ["CSS", "HTML"]
platforms = ["Web"]

[about_me]

date  = "2014-10-02T03:56:39+08:00"
draft = true
title = "ABOUT ME"

tags      = ["Me"]
languages = ["English"]

[about_the_site]

date = "2014-11-05T09:26:28+08:00"
draft = true
title = "ABOUT THE SITE"

tags      = ["Me"]
languages = ["English"]

